# SPDX-FileCopyrightText: James Turner <james@flightgear.org>
#
# SPDX-License-Identifier: GPL-2.0


variables:

  TEST_DATA_DIR: $CI_PROJECT_DIR/testFGData
  BUNDLED_DATA_DIR: $CI_PROJECT_DIR/bundledFGData

  PYTHON_VENV_DIR: /tmp/venv-dir
  PYTHON_VENV_BINDIR: $PYTHON_VENV_DIR/bin

# Do not run pipelines on forks. Run them on merge requests branches, tags
# and the protected branches.
workflow:
  rules:
    - if: $CI_PROJECT_NAMESPACE != "flightgear"
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_PROTECTED == "true"

# pre-commit setup adapted from the flightgear repository.
# There is an example at https://pre-commit.com/#gitlab-ci-example
.pre-commit-common:
  stage: test
  image: ${CI_REGISTRY}/flightgear/flightgear-ci-docker/pre-commit:latest
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit

pre-commit-merge:
  extends: .pre-commit-common
  script:
    - git fetch origin "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    - >
      pre-commit run --from-ref origin/"$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
      --to-ref "$CI_COMMIT_SHA"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  cache:
    paths:
      - ${PRE_COMMIT_HOME}

pre-commit:
  extends: .pre-commit-common
  script:
    - pre-commit run --all-files
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
  cache:
    paths:
      - ${PRE_COMMIT_HOME}

# minimal data for running FGTestSuite, keep this as small as possible
# since we frequently copy it to the code builders
create-test-data:
  stage: deploy

  script:
    - mkdir $TEST_DATA_DIR
    - cp *.xml $TEST_DATA_DIR
    - cp version $TEST_DATA_DIR

    - mkdir -p $TEST_DATA_DIR/AI/Aircraft
    - cp AI/Aircraft/*.xml $TEST_DATA_DIR/AI/Aircraft/
    - cp AI/*.xml $TEST_DATA_DIR/AI/

    - mkdir -p $TEST_DATA_DIR/ATC/
    - cp ATC/*.xml $TEST_DATA_DIR/ATC/

    - cp -r Environment Nasal Timezone Navaids Airports Input gui Translations $TEST_DATA_DIR

  artifacts:
    paths:
      - $TEST_DATA_DIR

  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"

# Create a Python venv in $PYTHON_VENV_DIR; inside the venv, install the
# 'flightgear' package from FGMeta-python.
.prepare-python-venv: &prepare-python-venv
  - |
    if [[ -e "$PYTHON_VENV_DIR" ]]; then
      echo "$PYTHON_VENV_DIR already exists before creating the venv!"
      exit 1
    fi
  - python3 -m venv "$PYTHON_VENV_DIR"
  - >
    "$PYTHON_VENV_BINDIR"/pip install
    git+https://gitlab.com/flightgear/fgmeta-python.git

validate-shaders:
  stage: test
  image: ${CI_REGISTRY}/flightgear/flightgear-ci-docker/pre-commit:latest
  allow_failure:
    exit_codes: 2 # warnings
  before_script:
    - *prepare-python-venv
  script:
    - '"$PYTHON_VENV_BINDIR"/fg-validate-shaders "$CI_PROJECT_DIR" || exit $?'

# XML files containing the <?FlightGear-tr?> processing instruction:
# check that contexts are declared, don't overlap, follow naming rules, etc.
validate-XML-translations:
  stage: test
  image: ${CI_REGISTRY}/flightgear/flightgear-ci-docker/pre-commit:latest
  allow_failure: false
  before_script:
    - *prepare-python-venv
  script:
    - >
      "$PYTHON_VENV_BINDIR"/fg-extract-translatable-strings check
      "$CI_PROJECT_DIR" || exit $?

# all the files from FGData which we bunlde with the application / image
# installers. Keep this small since this impacts file mirrors, code-signing,
# etc.
# create-bundled-data:
#   stage: deploy
#   variables:
#     AI_DIR: $BUNDLED_DATA_DIR/AI
#   script:
#     - mkdir $BUNDLED_DATA_DIR
#     - cp version *.xml $BUNDLED_DATA_DIR

#   # AI is a pain
#     - mkdir -p $AI_DIR/Aircraft
#     - cp AI/Aircraft/*.xml $AI_DIR/Aircraft/
#     - cp AI/*.xml $AI_DIR
    
#     # skip traffic, it's huge
#     #- cp -r AI/Traffic $AI_DIR

#     # do we need the yellow glider?

#   # all the straightforward dirs
#     - cp -r Environment Nasal Timezone Navaids Airports Input ATC 
#         Fonts Phi Protocol Shaders gui Translations 
#         Video Astro Compositor Effects Geodata Huds Lighting MP
#         Materials
#         $BUNDLED_DATA_DIR

#   # anything in Aircraft?

#   # ToDo: if we have a base version, then find all files which are changed
#   # since that tag in Git, 
#   # this is going to use 'git diff --name-only --diff-filter=AMR' and
#   # then copying all the resulting files over to $BUNDLED_DATA_DIR

#   artifacts:
#     paths:
#       - $BUNDLED_DATA_DIR

# disabled for now, too large

# create-base-package:
#   stage: deploy
#   variables:
#     OUT_DIR: $CI_PROJECT_DIR/FlightGear_BaseData
#   script:
#     - mkdir $OUT_DIR
#     - cp version $OUT_DIR

#     - cp -r AI Aircraft Textures Models Sounds $OUT_DIR

#     # ToDo: include BasePackage scenery
#   artifacts:
#     paths:
#       - $OUT_DIR
