# SPDX-License-Identifier: GPL-2.0-or-later
# SPDX-FileCopyrightText: 2025 Florent Rougon

repos:
  - repo: https://gitlab.com/flightgear/fgmeta-python.git
    rev: 1.1.0
    hooks:
      - id: fg-validate-propertylist-files
