# SPDX-License-Identifier: GPL-2.0-or-later
# SPDX-FileCopyrightText: 2025 Florent Rougon

repos:
  - repo: https://gitlab.com/flightgear/fgmeta-python.git
    rev: 33f5d91c9b781c1ca0fdf53cf5d0a25ec2caeadd
    hooks:
      - id: fg-validate-propertylist-files
