# SPDX-License-Identifier: GPL-2.0-or-later
# SPDX-FileCopyrightText: 2025 Florent Rougon

repos:
  - repo: https://gitlab.com/flightgear/fgmeta-python.git
    rev: cc3bd50d6ee0703292009f8901639fb45aca52ac
    hooks:
      - id: fg-validate-propertylist-files
